# permissions for end users to view fhes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fhe-viewer-role
rules:
- apiGroups:
  - fhe.redhat.com
  resources:
  - fhes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fhe.redhat.com
  resources:
  - fhes/status
  verbs:
  - get
